bases:
- ../base
namePrefix: dev-
commonLabels:
  app: devapp
commonAnnotations:
  circumstances: "made by kustomize dev section"
patchesStrategicMerge:
- env-and-secret.yaml

configMapGenerator:
- name: kustom-configmap
  literals:
  - ENV=DEV
  - COLOR=YELLOW
generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-nginx
  path: patch.yaml
