bases:
- ../base
namePrefix: prod-
commonLabels:
  app: prodapp
commonAnnotations:
  circumstances: "made by kustomize prod section specific prod image too"
images:
- name: nginx
  newName: my.image.registry/nginx
  newTag: 1.4.0
patchesStrategicMerge:
- env-and-secret.yaml

configMapGenerator:
- name: kustom-configmap
  literals:
  - ENV=PROD
  - COLOR=GREEN
generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-nginx
  path: patch.yaml
