apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgCuQlIzzwHTsH5GbZbB+hfeAoUf5fUShJV2dQCDgR0onx69E4bml7jQnUu1E2KAUFI7BJGYl3OhqniiibA/fJz1xhf/ra2tBDd1c7Ditqk1R6SSlZWbNLnrvpL5v8qMZpLpbM/RHktBYkf8maHxjxKGfJrXW/6Wz7Dcb+iOnzqmy0ZG0G+2U42dSLf0wuJVZVnl1Ng0/zafTLANGoI9dd6MGaHpVKHH/lfmADTCNkYX15xzmhTeX2VaXa3HnCKHcS3U96vPYUMu4jz3At1u4sglul4CMs4Bj9jwLs5rKW0JC+BHYbFNJCqp+av/yxOSogDxqOMvCSH92q0olAeMmyf3yun5nMGxAIctMxVEoxVncZ8ka6KRvgFgdCAHIyKK9aSgZlKcuUIDF74k4lU/kTM+0opFZD0DUIhubyC3y4dk+bBgXr2wP02fwHUt53aQt65YLA5bSsLPXYEKPbUsV5ExHRsyocKThjaWxdgqFN+fbb/aO0EtyAlkF+JwK+2Qd5w7BUtqT7g/BlFHRx/4eMbNrC7pHqBS6tbfNqpmQmvGY/+l0WkeAFVt2wP2mfzek9OVMdMIBnyaj9ZCOVM6LQ/VR6FsWUuxV1rWvgX/STGBrCArKuyhIO8QT0NQoV6EDw3rMADvugK+hKu+xDb2F4p16nZSTjzLhbsR3RXgflkWzuwtssgMHDmArVtRhefD33MUqNb+/ws=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

