apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgDyl8pYqX/IAI86SYuqgY0GqfrINglxnGNbkQYbsxhvOljYxIIDJoN9iTpd+WXuoajmUxcXGXnV39JuXrEogD9RNotANy1G7DXQWI4yA6feJzcua93EG1xq3W1JmCrzbha/fB7NsEkMa01U2sFpQ7YvoOtYvjpB3gNeGqqNVYPv/1RK8ugF1PTkfGnwdGzrzpDv9UvzynU32QEDXAoXueDPyWBTHYc4ScdOwDSoArNSRaJUThOOTajcOFdfFjWsCzQ7aaZUrk4OA6VJIf1dNf7NdGpM42xUNUQXlVKUnjtx5mLW/Gz+9x5w5CwukxHAwbjgZvpTXRqnvYXV5t3KOTCqwvlGp1xTMVLT5WK5U3tw8TB/n0GPMuLYQdKGBGpVAcRv2yMuy+pEgg7q7/D8Dhj6Pyh9WuSyHy7YatKRp1+Ot7m70b6g8RF8vqpDkD944QI8Z6GmlxuGKKpyeNOG99tPWwspXjE1YnMNLyv9sxEkkAT7PuYTdWVyrWq3i5FDYoZScZ0+zJP3NpRLqfiz65QXEK9nbvuVT64oA3cBtmisg4LSoGyKR4+KVQzHyH9K4/I/KjA8zaF+2SjcuFSgYwXmuooVNlcyfyGr/AnnIkiax9g2szZ0zU29xh7wRrumZVdxQcD7F4ytWfzYl1m1Iz8hGtOEpjkPQWfpi6E0CzbXvcFW2IESYL76z1igvKQvbynelmFrGkuwAw==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

